spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/casedb
        username: root
        password: 123456
        #初始化连接数量
        initialSize: 10
        #最大连接数量
        maxActive: 20
        #最小空闲连接
        minIdle: 1
        #超时等待时间以毫秒为单位
        maxWait: 60000
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        timeBetweenEvictionRunsMillis: 3600000
        minEvictableIdleTimeMillis: 300000
        #SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前
        validationQuery: SELECT 1 FROM DUAL
        #指明连接是否被空闲连接回收器(如果有)进行检验.
        #如果检测失败,则连接将被从池中去除.
        testWhileIdle: true
        #指明是否在从池中取出连接前进行检验,如果检验失败,
        #则从池中去除连接并尝试取出另一个.
        testOnBorrow: false
        #指明是否在归还到池中前进行检验 
        testOnReturn: false